### ISSUE TITLE
bunch of followers that i can't export

### ISSUE THREAD

**Issue by imankiyumarsi** [novitae/sterraxcyl#15]
such a good tool!
I have problem with exporting the followers username. i tested with 2 or 3 diffrent account several times but each time it's stop under 10000 usernames and i can't resume the exporting. part for exporting is not work for me.
the error is:
PrivateAccError: --username is a private account that you're not following.
after this function didn't go forward and stop. i followed the account but it's not working.

**Comment by novitae** [comment]
I don't understand where your issue is ...
- If it is during the followers username of your target scraping, then yes unfortunately instagram limits these action to a certain amount of followers you can get.
- And if you just requested for a follow the account but that it is still pending, it is normal that you don't have access to your target

**Comment by imankiyumarsi** [comment]
![Screenshot 2022-04-14 135554](https://user-images.githubusercontent.com/79364187/163356957-43ac5960-d4c1-4217-8560-cb36d0620603.png)
this is the command and error i got.

**Comment by novitae** [comment]
Weird error ... I'll try to figure out what is the problem if I start working again on this program.
For the moment it's not a problem since the error is probably due to the huge range of usernames you want to export that instagram doesn't allow, and I can't do anything about it, im sorry ...
