### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by hartmania** [novitae/sterraxcyl#7]
Excited to give the new update a spin!!

Trying to work through this login issue:
"Please check Instagram app for a security confirmation that it is you trying to login."

I keep acknowledging it was me but to no avail -- might be due to thinking it's a windows 10 phone (who has one of those, right?) -- if I figure it out will update....

<img width="424" alt="Screen Shot 2021-11-15 at 1 30 45 PM" src="https://user-images.githubusercontent.com/5727996/141856566-106bfbbb-dcde-4078-8d61-a3c87cea8291.png">

**Comment by novitae** [comment]
It is not especially due to your OS or anything, it is simply instagram detecting this activity and considering it weird.
What you should do is making a new instagram account, don't login with it on your phone, but login on the same computer  you run sterra. Instagram will save your computer's ip as a non-suspect ip, and you'll be able to login with sterra normally.

Btw you should login via sessionid instead of credentials : this method never fails.

Tell me if it works or not :)
